const mongoose = require("mongoose");
require("dotenv").config();

const Match = require("./models/Match");

const matches = [
  {
    opponent: "SK Beveren",
    date: new Date("2026-07-04"),
    time: "17:00",
    location: "Freethiel",
    home: true,
    competition: "Oefenwedstrijd",
    matchday: 1,
    status: "finished",
    homeScore: 1,
    awayScore: 8,
  },
  {
    opponent: "FCSM Latem",
    date: new Date("2026-07-26"),
    time: "16:00",
    location: "Uitwedstrijd",
    home: false,
    competition: "Beker van België",
    matchday: 1,
    status: "finished",
    homeScore: 1,
    awayScore: 2,
  },
  {
    opponent: "KSK Kallo",
    date: new Date("2026-07-28"),
    time: "19:30",
    location: "Uitwedstrijd",
    home: false,
    competition: "Oefenwedstrijd",
    matchday: 2,
    status: "finished",
    homeScore: 1,
    awayScore: 1,
  },
  {
    opponent: "Deurne Pirates",
    date: new Date("2026-07-29"),
    time: "19:30",
    location: "Uitwedstrijd",
    home: false,
    competition: "Oefenwedstrijd",
    matchday: 3,
    status: "finished",
    homeScore: 3,
    awayScore: 0,
  },
  {
    opponent: "KSC Blankenberge",
    date: new Date("2026-08-02"),
    time: "16:00",
    location: "Freethiel",
    home: true,
    competition: "Beker van België",
    matchday: 2,
    status: "finished",
    homeScore: 1,
    awayScore: 4,
  },
  {
    opponent: "KFC Jong Kruibeke",
    date: new Date("2026-08-05"),
    time: "20:00",
    location: "Freethiel",
    home: true,
    competition: "Oefenwedstrijd",
    matchday: 4,
    status: "finished",
    homeScore: 3,
    awayScore: 0,
  },
  {
    opponent: "KFC Sporting Sint-Gillis-Waas",
    date: new Date("2026-08-12"),
    time: "19:15",
    location: "Uitwedstrijd",
    home: false,
    competition: "Oefenwedstrijd",
    matchday: 5,
    status: "finished",
    homeScore: 1,
    awayScore: 3,
  },
  {
    opponent: "Koninklijk Berchem Sport",
    date: new Date("2026-08-16"),
    time: "15:00",
    location: "Uitwedstrijd",
    home: false,
    competition: "Oefenwedstrijd",
    matchday: 6,
    status: "finished",
    homeScore: 1,
    awayScore: 2,
  },
  {
    opponent: "Sparta Waasmunster",
    date: new Date("2026-08-20"),
    time: "20:00",
    location: "Freethiel",
    home: true,
    competition: "Oefenwedstrijd",
    matchday: 7,
    status: "finished",
    homeScore: null,
    awayScore: null,
  },
  {
    opponent: "VV Hulst",
    date: new Date("2026-08-22"),
    time: "14:30",
    location: "Uitwedstrijd",
    home: false,
    competition: "Oefenwedstrijd",
    matchday: 8,
    status: "finished",
    homeScore: 2,
    awayScore: 3,
  },
  {
    opponent: "SK Berlare",
    date: new Date("2026-08-29"),
    time: "20:00",
    location: "Freethiel",
    home: true,
    competition: "Competitie",
    matchday: 1,
    status: "finished",
    homeScore: 4,
    awayScore: 0,
  },
  {
    opponent: "SK Denderhoutem",
    date: new Date("2026-09-05"),
    time: "19:30",
    location: "Uitwedstrijd",
    home: false,
    competition: "Competitie",
    matchday: 2,
    status: "upcoming",
    homeScore: null,
    awayScore: null,
  },
  {
    opponent: "Evergem 2020",
    date: new Date("2026-09-12"),
    time: "20:00",
    location: "Freethiel",
    home: true,
    competition: "Competitie",
    matchday: 3,
    status: "upcoming",
    homeScore: null,
    awayScore: null,
  },
  {
    opponent: "Herleving Red Star Haasdonk",
    date: new Date("2026-09-19"),
    time: "20:00",
    location: "Uitwedstrijd",
    home: false,
    competition: "Competitie",
    matchday: 4,
    status: "upcoming",
    homeScore: null,
    awayScore: null,
  },
  {
    opponent: "VK Ninove",
    date: new Date("2026-09-26"),
    time: "20:00",
    location: "Freethiel",
    home: true,
    competition: "Competitie",
    matchday: 5,
    status: "upcoming",
    homeScore: null,
    awayScore: null,
  },
  {
    opponent: "SK Munkzwalm",
    date: new Date("2026-10-04"),
    time: "15:00",
    location: "Uitwedstrijd",
    home: false,
    competition: "Competitie",
    matchday: 6,
    status: "upcoming",
    homeScore: null,
    awayScore: null,
  },
  {
    opponent: "KVV Schelde Serskamp-Schellebelle",
    date: new Date("2026-10-10"),
    time: "20:00",
    location: "Freethiel",
    home: true,
    competition: "Competitie",
    matchday: 7,
    status: "upcoming",
    homeScore: null,
    awayScore: null,
  },
  {
    opponent: "KV Eendracht Aalter",
    date: new Date("2026-10-17"),
    time: "20:00",
    location: "Uitwedstrijd",
    home: false,
    competition: "Competitie",
    matchday: 8,
    status: "upcoming",
    homeScore: null,
    awayScore: null,
  },
  {
    opponent: "FCSM Latem",
    date: new Date("2026-10-24"),
    time: "19:30",
    location: "Uitwedstrijd",
    home: false,
    competition: "Competitie",
    matchday: 9,
    status: "upcoming",
    homeScore: null,
    awayScore: null,
  },
  {
    opponent: "VC Nokere-Kruishoutem",
    date: new Date("2026-10-31"),
    time: "21:00",
    location: "Freethiel",
    home: true,
    competition: "Competitie",
    matchday: 10,
    status: "upcoming",
    homeScore: null,
    awayScore: null,
  },
];

async function seedMatches() {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log("MongoDB verbonden!");

    await Match.deleteMany({});

    await Match.insertMany(matches);

    console.log(`${matches.length} wedstrijden toegevoegd!`);

    await mongoose.disconnect();
  } catch (error) {
    console.error("Fout:", error);
    process.exit(1);
  }
}

seedMatches();